# Generated by Django 2.1 on 2019-10-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Lng',
            field=models.FloatField(null=True),
        ),
    ]
